"""bin/install-skills.sh is how most people will adopt this repo - test it.

The guides are plain Markdown in `docs/guides/`, which is the source of truth.
This script renders them into the standard Agent Skills and Claude Code layouts
by default, or only a custom layout with --dest, and drops the `bin/eda.sh`
shim. Nothing here is required to *read* the guides.
"""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "bin" / "install-skills.sh"
GUIDE_DIR = ROOT / "docs" / "guides"
GUIDES = sorted(p.stem for p in GUIDE_DIR.glob("*.md") if p.stem != "README")
USER_SKILL_CONTENT = "Pre-existing skill content owned by the target project.\n"
USER_NOTES_CONTENT = "Unrelated notes owned by the target project.\n"
USER_MARKER_CONTENT = "Pre-existing marker content owned by the target project.\n"
INSTALL_MARKER_CONTENT = "created by kicad_skills/bin/install-skills.sh\n"
SHIM_MARKER_CONTENT = (
    "# Generated by kicad_skills/bin/install-skills.sh - runs the toolkit container.\n"
)

pytestmark = pytest.mark.skipif(shutil.which("bash") is None, reason="needs bash")


@pytest.fixture
def project(tmp_path):
    """A parent project with this repository vendored at tools/kicad_skills."""
    target = tmp_path / "my-board"
    submodule = target / "tools" / "kicad_skills"
    (submodule / "bin").mkdir(parents=True)
    shutil.copytree(GUIDE_DIR, submodule / "docs" / "guides")
    shutil.copy(SCRIPT, submodule / "bin" / "install-skills.sh")
    (submodule / "bin" / "eda.sh").write_text("#!/usr/bin/env bash\necho stub\n")
    (submodule / "bin" / "eda.sh").chmod(0o755)
    return target, submodule


def install(submodule, target, *args):
    return subprocess.run(
        ["bash", str(submodule / "bin" / "install-skills.sh"), "--target", str(target), *args],
        capture_output=True,
        text=True,
        check=True,
    )


def test_there_is_a_guide_for_every_area():
    assert set(GUIDES) == {
        "datasheet-analysis",
        "eda-environment",
        "kicad-design-gate",
        "kicad-fabrication-output",
        "kicad-pcb-authoring",
        "kicad-pcb-review",
        "kicad-schematic-authoring",
        "kicad-schematic-review",
        "spice-simulation",
    }


def test_every_guide_carries_the_header_a_tool_selects_on():
    """The YAML front matter is what lets a tool pick one guide out of the set."""
    for name in GUIDES:
        text = (GUIDE_DIR / f"{name}.md").read_text()
        assert text.startswith("---\n"), name
        header = text.split("---\n")[1]
        assert f"name: {name}\n" in header, f"{name}: front-matter name must match the filename"
        assert "description:" in header, name


def test_guides_are_rendered_into_both_standard_skill_layouts(project):
    target, submodule = project
    install(submodule, target)

    for root in (".agents", ".claude"):
        for name in GUIDES:
            skill = target / root / "skills" / name / "SKILL.md"
            assert skill.is_symlink(), f"{root}: {name}"
            # Relative, so the project can be moved or cloned anywhere.
            assert not os.path.isabs(os.readlink(skill))
            assert skill.read_text().startswith("---\n"), os.readlink(skill)


def test_the_generated_copy_tracks_the_guide(project):
    """A symlink, not a copy - editing the guide must not need a re-install."""
    target, submodule = project
    install(submodule, target)

    guide = submodule / "docs" / "guides" / f"{GUIDES[0]}.md"
    guide.write_text(guide.read_text() + "\nAn edit made after installing.\n")
    skill = target / ".claude" / "skills" / GUIDES[0] / "SKILL.md"
    assert "An edit made after installing." in skill.read_text()


def test_the_shim_forwards_to_the_submodule_wrapper(project):
    target, submodule = project
    install(submodule, target)

    shim = target / "bin" / "eda.sh"
    assert os.access(shim, os.X_OK)
    assert shim.stat().st_mode & 0o777 == 0o755
    result = subprocess.run([str(shim), "doctor"], capture_output=True, text=True, cwd=target)
    assert result.stdout.strip() == "stub", result.stderr


def test_the_shim_still_works_from_another_directory(project):
    target, submodule = project
    install(submodule, target)
    result = subprocess.run(
        [str(target / "bin" / "eda.sh")], capture_output=True, text=True, cwd=target.parent
    )
    assert result.stdout.strip() == "stub", result.stderr


def test_the_shim_quotes_special_characters_in_the_toolkit_path(project):
    target, submodule = project
    special_submodule = submodule.with_name("toolkit $repo `quoted`")
    submodule.rename(special_submodule)

    install(special_submodule, target, "--no-guides")

    shim = target / "bin" / "eda.sh"
    result = subprocess.run([str(shim)], capture_output=True, text=True, cwd=target, check=True)
    assert result.stdout.strip() == "stub", result.stderr


def test_a_dangling_shim_symlink_is_preserved_without_force(project):
    target, submodule = project
    (target / "bin").mkdir()
    shim = target / "bin" / "eda.sh"
    missing_target = target / "user-wrapper.sh"
    shim.symlink_to(Path("../user-wrapper.sh"))

    install(submodule, target, "--no-guides")

    assert shim.is_symlink()
    assert not missing_target.exists()


def test_force_unlinks_a_shim_symlink_without_touching_its_target(project):
    target, submodule = project
    (target / "bin").mkdir()
    shim_target = target / "user-wrapper.sh"
    shim_target.write_text(USER_SKILL_CONTENT)
    shim = target / "bin" / "eda.sh"
    shim.symlink_to(Path("../user-wrapper.sh"))

    install(submodule, target, "--no-guides", "--force")

    assert shim_target.read_text() == USER_SKILL_CONTENT
    assert shim.is_file()
    assert not shim.is_symlink()
    result = subprocess.run([str(shim)], capture_output=True, text=True, cwd=target, check=True)
    assert result.stdout.strip() == "stub", result.stderr


def test_install_rejects_a_symlinked_bin_directory(project):
    target, submodule = project
    external_bin = target.parent / "external-bin"
    external_bin.mkdir()
    (target / "bin").symlink_to(external_bin, target_is_directory=True)

    with pytest.raises(subprocess.CalledProcessError) as error:
        install(submodule, target, "--no-guides", "--force")

    assert "path component is a symlink: bin" in error.value.stderr
    assert not (external_bin / "eda.sh").exists()


def test_existing_entries_are_kept_unless_forced(project):
    target, submodule = project
    existing_skill = target / ".claude" / "skills" / GUIDES[0]
    existing_skill.mkdir(parents=True)
    (existing_skill / "SKILL.md").write_text(USER_SKILL_CONTENT)

    install(submodule, target)
    assert (existing_skill / "SKILL.md").read_text() == USER_SKILL_CONTENT

    install(submodule, target, "--force")
    assert (existing_skill / "SKILL.md").is_symlink()


@pytest.mark.parametrize("absolute", [False, True])
def test_legacy_symlinks_gain_ownership_markers(project, absolute):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    skill_dir.mkdir(parents=True)
    guide = submodule / "docs" / "guides" / f"{name}.md"
    link_target = guide if absolute else Path(os.path.relpath(guide, skill_dir))
    (skill_dir / "SKILL.md").symlink_to(link_target)

    result = install(submodule, target)

    marker = skill_dir / ".eda-toolkit-installed"
    assert f"migrated .claude/skills/{name} (legacy symlink)" in result.stdout
    marker_lines = marker.read_text().splitlines()
    assert marker_lines[0] == "created by kicad_skills/bin/install-skills.sh"
    assert marker_lines[1] == "adapter-type=symlink"
    assert marker_lines[2].startswith("adapter-sha256=")

    install(submodule, target, "--uninstall")
    assert not skill_dir.exists()


@pytest.mark.parametrize("adapter_type", ["symlink", "copy"])
def test_one_line_ownership_markers_gain_adapter_metadata(project, adapter_type):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    skill_dir.mkdir(parents=True)
    guide = submodule / "docs" / "guides" / f"{name}.md"
    skill = skill_dir / "SKILL.md"
    if adapter_type == "symlink":
        skill.symlink_to(Path(os.path.relpath(guide, skill_dir)))
    else:
        shutil.copy(guide, skill)
    marker = skill_dir / ".eda-toolkit-installed"
    marker.write_text(INSTALL_MARKER_CONTENT)

    result = install(submodule, target, "--dest", ".claude/skills", "--no-shim")

    assert f"migrated .claude/skills/{name} (ownership metadata)" in result.stdout
    marker_lines = marker.read_text().splitlines()
    assert marker_lines[1] == f"adapter-type={adapter_type}"
    assert marker_lines[2].startswith("adapter-sha256=")

    install(submodule, target, "--dest", ".claude/skills", "--no-shim", "--uninstall")
    assert not skill_dir.exists()


@pytest.mark.parametrize("replacement", ["file", "symlink"])
def test_one_line_markers_do_not_claim_replaced_adapters(project, replacement):
    target, submodule = project
    destination = ".claude/skills"
    name = GUIDES[0]
    skill_dir = target / destination / name
    skill_dir.mkdir(parents=True)
    skill = skill_dir / "SKILL.md"
    if replacement == "file":
        skill.write_text(USER_SKILL_CONTENT)
    else:
        user_skill = target / "user-skill.md"
        user_skill.write_text(USER_SKILL_CONTENT)
        skill.symlink_to(Path(os.path.relpath(user_skill, skill_dir)))
    marker = skill_dir / ".eda-toolkit-installed"
    marker.write_text(INSTALL_MARKER_CONTENT)

    install_result = install(submodule, target, "--dest", destination, "--no-shim")
    uninstall_result = install(submodule, target, "--dest", destination, "--no-shim", "--uninstall")

    assert f"skip {destination}/{name} (already exists" in install_result.stdout
    assert f"skip {destination}/{name} (adapter changed since installation)" in (
        uninstall_result.stdout
    )
    assert skill.read_text() == USER_SKILL_CONTENT
    assert skill.is_symlink() is (replacement == "symlink")
    assert marker.read_text() == INSTALL_MARKER_CONTENT


def test_migrating_a_marker_hardlink_does_not_modify_its_other_name(project):
    target, submodule = project
    destination = ".claude/skills"
    name = GUIDES[0]
    skill_dir = target / destination / name
    skill_dir.mkdir(parents=True)
    guide = submodule / "docs" / "guides" / f"{name}.md"
    (skill_dir / "SKILL.md").symlink_to(Path(os.path.relpath(guide, skill_dir)))
    marker_target = target / "shared-marker.txt"
    marker_target.write_text(INSTALL_MARKER_CONTENT)
    marker = skill_dir / ".eda-toolkit-installed"
    os.link(marker_target, marker)

    install(submodule, target, "--dest", destination, "--no-shim")

    assert marker_target.read_text() == INSTALL_MARKER_CONTENT
    assert marker.read_text().splitlines()[1] == "adapter-type=symlink"
    assert marker.stat().st_ino != marker_target.stat().st_ino


def test_an_unrelated_symlink_is_not_adopted_or_uninstalled(project):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    skill_dir.mkdir(parents=True)
    user_skill = target / "user-skill.md"
    user_skill.write_text(USER_SKILL_CONTENT)
    skill = skill_dir / "SKILL.md"
    skill.symlink_to(Path(os.path.relpath(user_skill, skill_dir)))

    install(submodule, target)
    assert not (skill_dir / ".eda-toolkit-installed").exists()

    install(submodule, target, "--uninstall")
    assert skill.is_symlink()
    assert skill.read_text() == USER_SKILL_CONTENT


@pytest.mark.parametrize("symlink", [False, True])
def test_a_marker_without_a_skill_is_preserved(project, symlink):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    skill_dir.mkdir(parents=True)
    marker = skill_dir / ".eda-toolkit-installed"
    if symlink:
        marker_target = target / "user-marker.txt"
        marker_target.write_text(USER_MARKER_CONTENT)
        marker.symlink_to(Path(os.path.relpath(marker_target, skill_dir)))
    else:
        marker.write_text(USER_MARKER_CONTENT)

    result = install(submodule, target)

    assert f"skip .claude/skills/{name} (ownership marker already exists" in result.stdout
    assert marker.read_text() == USER_MARKER_CONTENT
    assert marker.is_symlink() is symlink
    assert not (skill_dir / "SKILL.md").exists()


def test_force_unlinks_a_marker_symlink_without_touching_its_target(project):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    skill_dir.mkdir(parents=True)
    marker_target = target / "user-marker.txt"
    marker_target.write_text(USER_MARKER_CONTENT)
    marker = skill_dir / ".eda-toolkit-installed"
    marker.symlink_to(Path(os.path.relpath(marker_target, skill_dir)))

    install(submodule, target, "--force")

    assert marker_target.read_text() == USER_MARKER_CONTENT
    assert not marker.is_symlink()
    marker_lines = marker.read_text().splitlines()
    assert marker_lines[0] == "created by kicad_skills/bin/install-skills.sh"
    assert marker_lines[1] == "adapter-type=symlink"
    assert (skill_dir / "SKILL.md").is_symlink()


def test_force_rejects_a_marker_directory_before_creating_the_skill(project):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    marker = skill_dir / ".eda-toolkit-installed"
    marker.mkdir(parents=True)

    with pytest.raises(subprocess.CalledProcessError) as error:
        install(submodule, target, "--force")

    assert "cannot replace marker directory" in error.value.stderr
    assert marker.is_dir()
    assert not (skill_dir / "SKILL.md").exists()


def test_force_rejects_a_skill_directory_before_removing_the_marker(project):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    skill = skill_dir / "SKILL.md"
    skill.mkdir(parents=True)
    marker = skill_dir / ".eda-toolkit-installed"
    marker.write_text(USER_MARKER_CONTENT)

    with pytest.raises(subprocess.CalledProcessError) as error:
        install(submodule, target, "--force")

    assert "cannot replace directory .claude/skills" in error.value.stderr
    assert skill.is_dir()
    assert marker.read_text() == USER_MARKER_CONTENT


def test_force_preflights_every_skill_before_replacing_any_entry(project):
    target, submodule = project
    destination = "custom-skills"
    first_dir = target / destination / GUIDES[0]
    first_dir.mkdir(parents=True)
    first_skill = first_dir / "SKILL.md"
    first_marker = first_dir / ".eda-toolkit-installed"
    first_skill.write_text(USER_SKILL_CONTENT)
    first_marker.write_text(USER_MARKER_CONTENT)
    later_marker = target / destination / GUIDES[-1] / ".eda-toolkit-installed"
    later_marker.mkdir(parents=True)

    with pytest.raises(subprocess.CalledProcessError):
        install(submodule, target, "--dest", destination, "--no-shim", "--force")

    assert first_skill.read_text() == USER_SKILL_CONTENT
    assert first_marker.read_text() == USER_MARKER_CONTENT


def test_copy_mode_vendors_the_guides(project):
    target, submodule = project
    install(submodule, target, "--copy")
    skill = target / ".claude" / "skills" / GUIDES[0] / "SKILL.md"
    assert not skill.is_symlink()
    assert skill.read_text().startswith("---\n")


def test_guides_can_be_installed_anywhere(project):
    target, submodule = project
    install(submodule, target, "--dest", "docs/circuit-design", "--copy")

    assert (target / "docs" / "circuit-design" / GUIDES[0] / "SKILL.md").exists()
    assert not (target / ".agents").exists()
    assert not (target / ".claude").exists()


def test_a_destination_with_whitespace_is_not_split(project):
    target, submodule = project
    destination = "agent skills"
    install(submodule, target, "--dest", destination)

    skill = target / destination / GUIDES[0] / "SKILL.md"
    assert skill.is_symlink()
    assert skill.read_text().startswith("---\n")
    assert not (target / "agent").exists()
    assert not (target / "skills").exists()

    install(submodule, target, "--dest", destination, "--uninstall")
    assert not (target / destination).exists()


def test_redundant_destination_separators_and_dot_components_are_normalized(project):
    target, submodule = project
    result = install(submodule, target, "--dest", "./a//nested rules/./")

    skill = target / "a" / "nested rules" / GUIDES[0] / "SKILL.md"
    assert f"installed a/nested rules/{GUIDES[0]}/SKILL.md" in result.stdout
    assert skill.is_symlink()
    assert skill.read_text().startswith("---\n")

    install(submodule, target, "--dest", "./a//nested rules/./", "--uninstall")
    assert not (target / "a").exists()


@pytest.mark.parametrize(
    "destination",
    ["../escaped", "a/../../escaped", "/absolute", "C:/absolute", "..\\escaped"],
)
def test_destinations_cannot_escape_the_target(project, destination):
    target, submodule = project

    with pytest.raises(subprocess.CalledProcessError):
        install(submodule, target, "--dest", destination, "--no-shim")

    assert not (target.parent / "escaped").exists()
    assert not (target / "absolute").exists()


def test_install_rejects_a_symlinked_destination_without_touching_its_target(project):
    target, submodule = project
    external_layout = target.parent / "external-layout"
    external_layout.mkdir()
    (target / "custom-skills").symlink_to(external_layout, target_is_directory=True)

    with pytest.raises(subprocess.CalledProcessError) as error:
        install(submodule, target, "--dest", "custom-skills", "--no-shim", "--force")

    assert "path component is a symlink: custom-skills" in error.value.stderr
    assert list(external_layout.iterdir()) == []


@pytest.mark.parametrize("action", ["install", "uninstall"])
def test_a_symlinked_skill_directory_is_never_traversed(project, action):
    target, submodule = project
    destination = "custom-skills"
    name = GUIDES[0]
    layout = target / destination
    layout.mkdir()
    external_skill = target.parent / f"external-skill-{action}"
    external_skill.mkdir()
    external_marker = external_skill / ".eda-toolkit-installed"
    external_marker.write_text(INSTALL_MARKER_CONTENT)
    external_adapter = external_skill / "SKILL.md"
    external_adapter.write_text(USER_SKILL_CONTENT)
    (layout / name).symlink_to(external_skill, target_is_directory=True)

    arguments = ["--dest", destination, "--no-shim"]
    if action == "install":
        arguments.append("--force")
        with pytest.raises(subprocess.CalledProcessError):
            install(submodule, target, *arguments)
    else:
        arguments.append("--uninstall")
        install(submodule, target, *arguments)

    assert external_marker.read_text() == INSTALL_MARKER_CONTENT
    assert external_adapter.read_text() == USER_SKILL_CONTENT


def test_a_nested_destination_still_gets_relative_symlinks(project):
    target, submodule = project
    install(submodule, target, "--dest", "a/b/c")

    skill = target / "a" / "b" / "c" / GUIDES[0] / "SKILL.md"
    assert skill.is_symlink()
    assert not os.path.isabs(os.readlink(skill))
    assert skill.read_text().startswith("---\n"), os.readlink(skill)


def test_the_cli_can_be_installed_without_any_guides(project):
    target, submodule = project
    install(submodule, target, "--no-guides")

    assert (target / "bin" / "eda.sh").exists()
    assert not (target / ".agents").exists()
    assert not (target / ".claude").exists()


def test_uninstall_removes_what_it_installed(project):
    target, submodule = project
    install(submodule, target)
    keep = target / "hardware.txt"
    keep.write_text("Target project content.\n")

    install(submodule, target, "--uninstall")
    assert not (target / ".agents").exists()
    assert not (target / ".claude").exists()  # including the directory it created
    assert not (target / "bin" / "eda.sh").exists()
    assert keep.exists()
    # the guides themselves are untouched - they are the source, not a copy
    assert (submodule / "docs" / "guides" / f"{GUIDES[0]}.md").exists()


@pytest.mark.parametrize(
    ("flag", "guides_remain", "shim_remains"),
    [("--no-shim", False, True), ("--no-guides", True, False)],
)
def test_uninstall_respects_component_selection_flags(project, flag, guides_remain, shim_remains):
    target, submodule = project
    install(submodule, target)

    install(submodule, target, "--uninstall", flag)

    skill = target / ".agents" / "skills" / GUIDES[0] / "SKILL.md"
    assert (skill.exists() or skill.is_symlink()) is guides_remain
    assert (target / "bin" / "eda.sh").exists() is shim_remains


def test_uninstall_removes_an_adapter_whose_source_guide_was_deleted(project):
    target, submodule = project
    destination = "custom-skills"
    name = GUIDES[0]
    install(submodule, target, "--dest", destination, "--no-shim")
    (submodule / "docs" / "guides" / f"{name}.md").unlink()

    install(submodule, target, "--dest", destination, "--no-shim", "--uninstall")

    assert not (target / destination / name).exists()


def test_uninstall_preserves_a_user_shim_that_mentions_the_installer(project):
    target, submodule = project
    (target / "bin").mkdir()
    shim = target / "bin" / "eda.sh"
    content = "#!/usr/bin/env bash\n# Run install-skills.sh separately when needed.\necho user\n"
    shim.write_text(content)

    install(submodule, target, "--uninstall", "--no-guides")

    assert shim.read_text() == content


def test_uninstall_preserves_an_owned_looking_shim_symlink(project):
    target, submodule = project
    (target / "bin").mkdir()
    shim_target = target / "user-wrapper.sh"
    content = f"#!/usr/bin/env bash\n{SHIM_MARKER_CONTENT}echo user\n"
    shim_target.write_text(content)
    shim = target / "bin" / "eda.sh"
    shim.symlink_to(Path("../user-wrapper.sh"))

    install(submodule, target, "--uninstall", "--no-guides")

    assert shim.is_symlink()
    assert shim_target.read_text() == content


def test_uninstall_does_not_traverse_a_symlinked_bin_directory(project):
    target, submodule = project
    external_bin = target.parent / "external-bin"
    external_bin.mkdir()
    shim = external_bin / "eda.sh"
    content = f"#!/usr/bin/env bash\n{SHIM_MARKER_CONTENT}echo user\n"
    shim.write_text(content)
    (target / "bin").symlink_to(external_bin, target_is_directory=True)

    install(submodule, target, "--uninstall", "--no-guides")

    assert shim.read_text() == content


def test_uninstall_preserves_a_skill_the_installer_skipped(project):
    target, submodule = project
    existing_skill = target / ".agents" / "skills" / GUIDES[0]
    existing_skill.mkdir(parents=True)
    (existing_skill / "SKILL.md").write_text(USER_SKILL_CONTENT)
    (existing_skill / "notes.txt").write_text(USER_NOTES_CONTENT)

    install(submodule, target)
    install(submodule, target, "--uninstall")

    assert (existing_skill / "SKILL.md").read_text() == USER_SKILL_CONTENT
    assert (existing_skill / "notes.txt").read_text() == USER_NOTES_CONTENT


@pytest.mark.parametrize("replacement", ["file", "symlink"])
def test_uninstall_preserves_a_replaced_installed_adapter(project, replacement):
    target, submodule = project
    destination = ".claude/skills"
    name = GUIDES[0]
    install(submodule, target, "--dest", destination, "--no-shim")
    skill_dir = target / destination / name
    skill = skill_dir / "SKILL.md"
    skill.unlink()
    if replacement == "file":
        skill.write_text(USER_SKILL_CONTENT)
    else:
        user_skill = target / "user-skill.md"
        user_skill.write_text(USER_SKILL_CONTENT)
        skill.symlink_to(Path(os.path.relpath(user_skill, skill_dir)))

    result = install(submodule, target, "--dest", destination, "--no-shim", "--uninstall")

    assert f"skip {destination}/{name} (adapter changed since installation)" in result.stdout
    assert skill.read_text() == USER_SKILL_CONTENT
    assert skill.is_symlink() is (replacement == "symlink")
    assert (skill_dir / ".eda-toolkit-installed").exists()


def test_uninstall_preserves_a_modified_installed_copy(project):
    target, submodule = project
    destination = ".claude/skills"
    name = GUIDES[0]
    install(submodule, target, "--dest", destination, "--no-shim", "--copy")
    skill_dir = target / destination / name
    skill = skill_dir / "SKILL.md"
    skill.write_text(USER_SKILL_CONTENT)

    result = install(submodule, target, "--dest", destination, "--no-shim", "--uninstall")

    assert f"skip {destination}/{name} (adapter changed since installation)" in result.stdout
    assert skill.read_text() == USER_SKILL_CONTENT
    assert (skill_dir / ".eda-toolkit-installed").exists()


def test_uninstall_does_not_trust_a_marker_symlink(project):
    target, submodule = project
    name = GUIDES[0]
    skill_dir = target / ".claude" / "skills" / name
    skill_dir.mkdir(parents=True)
    skill = skill_dir / "SKILL.md"
    skill.write_text(USER_SKILL_CONTENT)
    marker_target = target / "owned-looking-marker.txt"
    marker_target.write_text(INSTALL_MARKER_CONTENT)
    marker = skill_dir / ".eda-toolkit-installed"
    marker.symlink_to(Path(os.path.relpath(marker_target, skill_dir)))

    install(submodule, target, "--uninstall", "--no-shim")

    assert skill.read_text() == USER_SKILL_CONTENT
    assert marker.is_symlink()
    assert marker_target.read_text() == INSTALL_MARKER_CONTENT


def test_uninstall_keeps_unrelated_files_added_to_an_installed_skill(project):
    target, submodule = project
    install(submodule, target)
    skill_dir = target / ".agents" / "skills" / GUIDES[0]
    notes = skill_dir / "notes.txt"
    notes.write_text(USER_NOTES_CONTENT)

    install(submodule, target, "--uninstall")

    assert notes.read_text() == USER_NOTES_CONTENT
    assert not (skill_dir / "SKILL.md").exists()
    assert not (skill_dir / ".eda-toolkit-installed").exists()


def test_installing_into_this_checkout_renders_the_adapter_but_no_shim(tmp_path):
    """Standalone use: `make skills` targets the repository itself."""
    checkout = tmp_path / "kicad_skills"
    (checkout / "bin").mkdir(parents=True)
    shutil.copytree(GUIDE_DIR, checkout / "docs" / "guides")
    shutil.copy(SCRIPT, checkout / "bin" / "install-skills.sh")

    subprocess.run(
        ["bash", str(checkout / "bin" / "install-skills.sh")],
        capture_output=True,
        text=True,
        check=True,
    )
    assert (checkout / ".agents" / "skills" / GUIDES[0] / "SKILL.md").is_symlink()
    assert (checkout / ".claude" / "skills" / GUIDES[0] / "SKILL.md").is_symlink()
    assert not (checkout / "bin" / "eda.sh").exists()  # it already has the real one


@pytest.mark.parametrize("directory", [".agents/skills", ".claude/skills"])
def test_the_generated_directories_are_not_tracked(directory):
    """Skill layouts are adapters; docs/guides/ is what gets reviewed."""
    ignored = subprocess.run(["git", "check-ignore", "-q", f"{directory}/x/SKILL.md"], cwd=ROOT)
    assert ignored.returncode == 0, f"{directory}/ must stay git-ignored"
